### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Sboursen**
## Description

In this milestone, I built the setup for the LeaderBoard API project. It is necessary to note that I used the following stack for this project:

- `Webpack5 `with an `HTML` template and `CSS extractor`.
- `TailWindCSS` for styling, therefore the `@rules` linter errors were **ignored**.
- Modular ES6 `JavaScript`.
- `JEST` to run a few unit tests.

### General requirements

- [x] There are no linter errors.
- [x] Followed the **Gitflow**.
- [x] The documentation is professional.

### Milestone requirements

- [x] Follow the provided template
- [x] Use webpack
- [x] Use Gitflow
- [x] Use ES6 modules
- [x] Don't make API calls (I used a mock API)

### Additional notes
ScreenShot
image

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Review by medaminedev66 — CHANGES_REQUESTED** [review]
Hi @Sboursen 😃, :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- ✔️The repo looks professional
- ✔️Gitflow best practices have been followed
- ✔️You have a descriptive PR
- ✔️Webpack dev server is set up and running with no errors

## Required Changes ♻️

- [x] Kindly add more information about your project to README so your project is documented professionally.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sboursen** [comment]
Hi
Thank you the feedback
I didn't notice that it was missing
thanks

**Comment by Sboursen** [comment]
Hi
Thank you for the feedback
I didn't notice that it was missing
thanks

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @Sboursen,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sboursen** [comment]
Thank you @TedLivist for the approval :+1:

**Pull request merged**
